### PR TITLE
Version numbers 2

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
The best two options I see so far are:

1) always write a backup file with

    sed -i.bak -e '...' filename

2) use Perl.  This seems really heavy, though.  :(

**Comment by cperciva** [comment]
Seriously?  *grumble*

Maybe we need to go back to sed + mv after all.

And yes, I'd like anyone to be able to run 'make publish' -- unlike 'make all' I'm willing to demand that they have BSD make since they can invoke it as bmake, but I can't demand that sed is BSD sed.

**Comment by gperciva** [comment]
if we *do* go back to sed+mv, can we assume that they have a /tmp?  Apparently `mktemp` is not in POSIX, and is missing from Solaris 9 at least.

or do we just write to "our-filename-sed-repace.tmp" in the ${PKG}-{VERSION}/ directory?

**Comment by cperciva** [comment]
No harm in writing into the staging directory.  Let's make it

    sed -e ... < file > file.new
    mv file.new file

**Comment by gperciva** [comment]
done, pushed to a separate branch.

**Pull request closed without merging**
