### PR TITLE
Add option to bind outgoing address

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
The build failure is due to github's deliberate brownouts of macOS 10.15; I'll re-trigger the checks after we've merged #365.

**Comment by gperciva** [comment]
Ok, ready for review.

**Comment by cperciva** [comment]
Do you want to add a CHANGELOG entry for this now, or later?

**Comment by cperciva** [comment]
Never mind I just saw you included it in the man page update.

**Pull request merged**
