### PR TITLE
restore proper version of spipe*/Makefile

### PR DESCRIPTION
**Pull request by gperciva**
alternatively, you might want to ignore these files in git; there isn't much point tracking auto-generated files.

### CODE REVIEW

**Comment by cperciva** [comment]
Huh, this is weird.  Did you generate these via 'make Makefiles'?  I wonder if your make is handling variable expansion differently from FreeBSD's make.

But I do want them in the tree, because if people check out this tree on linux I want them to have the makefiles they need -- they might not be able to (easily) regenerate them.

**Comment by gperciva** [comment]
I did
    bmake publish VERSION=mine
and those files were changed.  I figured that ${PROG}.1 was a more "git
master"-ish thing to have.

(incidently, I created this comment by hitting "reply" in my email
client)

- Graham

**Comment by cperciva** [comment]
Ok, something weird going on here.  Can you:

    cd spipe && bmake -f Makefile.BSD -V MAN1

and tell me what it returns?

**Comment by gperciva** [comment]
$ cd spipe && bmake -f Makefile.BSD -V MAN1
${PROG}.1

**Comment by gperciva** [comment]
if I change Makefile.BSD to:

    # Program name.
    PROG    =       spipe
    MAN1    :=      ${PROG}.1

then I get:

    gperciva@gin: ~/src/spiped/spipe (master)
    $ bmake -f Makefile.BSD -V MAN1
    spipe.1

**Comment by cperciva** [comment]
Interesting... yes, definitely different behaviour between FreeBSD and NetBSD make -V.  I wonder if this is a known issue?

The := option looks like it's going to be the right way of handling this though.  I'll take care of it in a bit.

**Comment by cperciva** [comment]
Can you check out the latest master, run

    bmake Makefiles
    git diff

and tell me if anything changed?  I *think* my recent commit works around the NetBSD/FreeBSD make incompatibility.

**Comment by gperciva** [comment]
Done, and no changes.

**Comment by cperciva** [comment]
Perfect, we don't need this then.

**Pull request closed without merging**
