### PR TITLE
Switch to container based Travis infrastructure

### PR DESCRIPTION
**Pull request by TimWolla**
This is a superset of #86, which is a necessary requirement for this one. 

Using the container based infrastructure allows for faster builds (not that it would really matter for this project) and reduces the load on the free service provided by Travis and thus should be preferred.

### CODE REVIEW

**Comment by TimWolla** [comment]
This is blocked by: https://github.com/travis-ci/apt-package-whitelist/pull/559

Comment if you're generally willing to merge this one, no need to bother the Travis folks unnecessarily.

**Comment by cperciva** [comment]
Looks reasonable to me subject to it working (which it doesn't yet, I assume due to the whitelisting issue you mentioned).

**Comment by TimWolla** [comment]
> which it doesn't yet, I assume due to the whitelisting issue you mentioned

Your assumption is correct: https://travis-ci.org/Tarsnap/spiped/jobs/161430950#L130

They're doing this as there might be possible escape vectors from containers when you're root, as you share the host / kernel. I just asked for an update / review in the whitelist's pull request.

**Comment by gperciva** [comment]
Once #97 is accepted (after #110 and #104), this PR will be unnecessary, as it also switches to the container-based Travis-CI infrastructure.

**Comment by cperciva** [comment]
This can be closed now, right?

**Comment by gperciva** [comment]
Well, we haven't been able to switch yet.  (I switched scrypt, but we can't switch spiped until nmap's `ncat` is replaced)

**Comment by cperciva** [comment]
Oh, I got confused because the other PRs weren't open any more.

**Comment by gperciva** [comment]
Closing this because it's handled by #97.

**Pull request closed without merging**
