### PR TITLE
checking CFLAGS_DEFAULT

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Different attempt at resolving #235; use instead of #236.

**Comment by cperciva** [comment]
I'm not sure I like how this is set up.  I was thinking that we could have a `posix-cflags-filter.sh` file which is created which is either empty or changes the value of CFLAGS, then that can be sourced after the `export CFLAGS="$${CFLAGS:-${CFLAGS_DEFAULT}}";` line.

**Comment by gperciva** [comment]
How obvious would the definition of `CFLAGS_DEFAULT` be, though?

I started off with something that occasionally changed the value of `CFLAGS_DEFAULT` (i.e. "if necessary"), but then I remembered that "cute" or "smart" build systems deserve all the hate they get.  I mean, I could definitely imagine myself:
1. compiling on some platform and getting a build failure.
2. change the `CFLAGS_DEFAULT` in `Makefile`.
3. try to compile again.
4. spend the next 20 minutes grasping at increasingly unlikely bugs in the OS, before I noticed that the value of `CFLAGS_DEFAULT` which was getting passed to the subdirectory `Makefile`s wasn't the same as its definition in the top-level `Makefile`.

I think that it would be much safer if there were different variable names for "what the user (or developers) suggests for the defaults" vs. "the default values that we're actually using".  I'm not wedded to `CFLAGS_DEFAULT_CHECKED`; we could change thE variables to `CFLAGS_DEFAULT_PRE` and `_post, or call the first one `_SUGGESTED`, or... well, I'm not fussy about the exact names.

**Comment by cperciva** [comment]
I'm not talking about changing `CFLAGS_DEFAULT`.  I'm talking about printing "WARNING: POSIX violation: make's CC doesn't understand -O2" and then stripping `-O2` from `CFLAGS`.

**Comment by cperciva** [comment]
I was thinking something like the filter-O2 branch I just pushed.  But that might not be enough to unbreak opensuse anyway. :-(

**Pull request closed without merging**
