### PR TITLE
spiped: add --syslog to send warnp messages to syslog

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This was prompted by #248.  However, you said that "the change should occur immediately after daemonizing", which I'm not certain about.  I would have thought that the change should happen immediately above `events_spin()`, i.e. after all the initialization is finished.  For example, would we ever want "Failed to start graceful_shutdown timer" to appear in syslog as opposed to stderr?

This PR switches to syslog just above `events_spin()`.  If you're certain that you want it immediately after daemonizing (in both places), I can change it accordingly.

**Comment by gperciva** [comment]
Another question: I went with `-l` (that's a lower-case L) because all the other spiped options are lower-case letters.  But I'm now thinking that it would be clearer to call it `--syslog`.

(This is particularly because I glanced at the list of PRs, saw a "negative one", and got really confused because I didn't remember doing that.)

**Comment by cperciva** [comment]
Once a program has daemonized, it is very likely that stderr either goes nowhere (someone starts a daemon and then exits their login shell) or goes somewhere actively harmful (someone starts a daemon and then opens an editor; their screen gets partially overwritten by the warning message).

**Comment by cperciva** [comment]
And yes, I agree with `--syslog` for this purpose.

**Comment by cperciva** [comment]
I assume you know what needs to be revised here and you're not waiting for me?

**Comment by gperciva** [comment]
It was mainly waiting on 0b9b5fa.  I also had it as waiting for #272, but in retrospect it doesn't actually need to delay until then.

Ready for merge.

**Comment by cperciva** [comment]
Commit message needs s/-l/--syslog/.

**Comment by gperciva** [comment]
Oops, fixed.  Also speaking of "oops", I just noticed that this branch is called `log-stdout` instead of `log-syslog`.

I'm happy to upload a new branch and create a new PR, or we could just accept that the merge commit message will be a bit misleading.  (We haven't worried about merge commits in the past.)

**Pull request merged**
