### PR TITLE
Coverity nitpicks

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Two nitpicks and one real flaw; all in test code.

**Comment by cperciva** [comment]
Wasn't coverity complaining about pthread_join ?

**Comment by gperciva** [comment]
Oh right, oops. I'm used to github, which displays comments below the line, instead of above it.

**Comment by gperciva** [comment]
Updated.  I kept the "check pthread_cancel" part, even though coverity-scan wasn't actually complaining about it, because I imagine that in a few months it would do anyway.

**Pull request merged**
